name: Test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Uv and set up Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
      - name: Install the project dependencies
        run: uv sync --locked --all-extras --dev
      - name: Run tests
        run: uv run pytest tests
